on: [push]

name: CI for 'ascii' and related libraries

jobs:
  build:
    name: Build all the packages
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        ghc: ['8.10.1', '8.8.1', '8.6.5', '8.4.3']
        cabal: ['3.0.0.0']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Build all packages
        run: cabal build all
